name: 'envirometrics'
description: 'Application de monitoring environnemental IoT.'
publish_to: 'none'
version: 1.0.4

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  # Pour effectuer les requêtes GET 
  http: ^1.6.0
  # Pour les graphiques de température, humidité et CO2 
  fl_chart: ^1.2.0 
  # Pour afficher des jauges modernes
  syncfusion_flutter_gauges: ^32.2.7
  # Pour gérer l'état
  provider: ^6.1.5
  # Pour formater les dates reçues de l'API 
  intl: ^0.20.2

  shared_preferences: ^2.5.5
  
  wakelock_plus: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  msix: ^3.16.13

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png" # Le chemin vers ton logo
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff" # Couleur de fond pour le PWA
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png

# flutter clean
# flutter pub get
# flutter pub run flutter_launcher_icons

# Build windows installer : flutter pub run msix:create

# Build batch :
#dart pub global activate flutter_distributor

# windows:
#   & "C:\Users\lukas\AppData\Local\Pub\Cache\bin\flutter_distributor.bat" release --name dev     
# debian :      
#     ~/.pub-cache/bin/flutter_distributor release --name dev