services:

  api-python:
    build: ./api_python
    container_name: api_fastapi
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - iot_network

  api-go:
    build: ./api_go
    container_name: api_fiber_go
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      TZ: Europe/Zurich
    depends_on:
      - db
    networks:
      - iot_network

  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Zurich
    volumes:
      - ${PATH_BDD}:/var/lib/mysql
    networks:
      - iot_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Europe/Zurich
    depends_on:
      - db
    networks:
      - iot_network

  serveur-web:
      image: nginx:alpine
      container_name: nginx_proxy
      restart: always
      ports:
        - "8080:80"
      volumes:
        - ./frontend_web:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - api-python
        - api-go # <-- Ajouté ici pour que Nginx attende Go aussi
      networks:
        - iot_network

networks:
  iot_network:
    driver: bridge
