services:

  api-python:
    build: ./api_python
    container_name: api_fastapi
    restart: always
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:       
      - iot_network

  db:
    image: mariadb:latest
    container_name: mariadb_server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      TZ: Europe/Zurich
    volumes:
      - ${PATH_BDD}:/var/lib/mysql
    networks:
      - iot_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin_gui
    restart: always
    ports:
      - "${PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: Europe/Zurich
    depends_on:
      - db
    networks:
      - iot_network

  serveur-web:
      image: nginx:alpine
      container_name: nginx_proxy
      restart: always
      ports:
        - "8080:80" # Seul Nginx est exposé sur le réseau
      volumes:
        - ./frontend_web:/usr/share/nginx/html # Vos fichiers Flutter
        - ./nginx.conf:/etc/nginx/conf.d/default.conf # La configuration
      depends_on:
        - api-python
      networks:
        - iot_network

networks:
  iot_network:
    driver: bridge


##### .env file exemple #####
# --- CONFIGURATION MARIADB ---
#DB_ROOT_PASSWORD=pass
#DB_NAME=EnviroMetrics
#DB_USER=admin
#DB_PASSWORD=pass
#
## --- CONFIGURATION RÉSEAU & PORTS ---
#PORT_PHPMYADMIN=1889
#PORT_MQTT=1883
#PORT_MQTT_WS=9001
#
## --- CHEMINS DES DONNÉES (Facultatif) ---
#PATH_BDD=./BDD
#PATH_MOSQUITTO=./mosquitto
