
server {
    listen 80;
    server_name localhost;

    # 1. Servir l'application Flutter Web
    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Nécessaire pour le routing interne de Flutter Web
        try_files $uri $uri/ /index.html; 
    }

    # 2. Rediriger les requêtes API vers FastAPI
    # (Flutter devra appeler http://IP_RASPBERRY/api/mesures)
    location /api/ {
        proxy_pass http://api_fastapi:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Redirection transparente des anciens liens PHP vers la nouvelle API
    # Intercepter l'ESP32 et l'envoyer à FastAPI
    location = /SendDB.php {
        proxy_pass http://api_fastapi:80/SendDB.php$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Intercepter les anciennes applications Flutter (Rétrocompatibilité)
    location = /get_mesures.php {
        proxy_pass http://api_fastapi:80/get_mesures.php$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location = /get_appareils.php {
        proxy_pass http://api_fastapi:80/get_appareils.php$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}