display_name: EnviroMetrics
package: envirometrics
maintainer: Lukas <lukas.hofer.ju@gmail.com>
summary: "Application de monitoring environnemental IoT."
description: "Application de monitoring environnemental IoT."
categories: "Utility;"
icon: assets/images/logo.png
